/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.empresa.controleproducao.view;

/**
 *
 * @author Ramon
 */
public class MenuPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalView
     */
    public MenuPrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cadastrar = new javax.swing.JMenu();
        cadastrar_cliente = new javax.swing.JMenuItem();
        cadastrar_produção = new javax.swing.JMenuItem();
        editar = new javax.swing.JMenu();
        editar_cliente = new javax.swing.JMenuItem();
        editar_produção = new javax.swing.JMenuItem();
        listar = new javax.swing.JMenu();
        listar_cliente = new javax.swing.JMenuItem();
        listar_produção = new javax.swing.JMenuItem();
        Sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Costa Pereira");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("Costa Pereira");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("Torrefação");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(12, 12, 12))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        cadastrar.setText("Cadastrar");
        cadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cadastrar_cliente.setText("Cliente");
        cadastrar_cliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cadastrar_cliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cadastrar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_clienteActionPerformed(evt);
            }
        });
        cadastrar.add(cadastrar_cliente);

        cadastrar_produção.setText("Produção");
        cadastrar_produção.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cadastrar_produção.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cadastrar_produção.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_produçãoActionPerformed(evt);
            }
        });
        cadastrar.add(cadastrar_produção);

        jMenuBar1.add(cadastrar);

        editar.setText("Editar");
        editar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        editar_cliente.setText("Cliente");
        editar_cliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        editar_cliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_clienteActionPerformed(evt);
            }
        });
        editar.add(editar_cliente);

        editar_produção.setText("Produção");
        editar_produção.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        editar_produção.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editar_produção.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_produçãoActionPerformed(evt);
            }
        });
        editar.add(editar_produção);

        jMenuBar1.add(editar);

        listar.setText("Listar");
        listar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        listar_cliente.setText("Cliente");
        listar_cliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        listar_cliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        listar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listar_clienteActionPerformed(evt);
            }
        });
        listar.add(listar_cliente);

        listar_produção.setText("Produção");
        listar_produção.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        listar_produção.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        listar_produção.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listar_produçãoActionPerformed(evt);
            }
        });
        listar.add(listar_produção);

        jMenuBar1.add(listar);

        Sair.setText("Sair");
        Sair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMouseClicked(evt);
            }
        });
        jMenuBar1.add(Sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_SairMouseClicked

    private void cadastrar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_clienteActionPerformed
        this.dispose();
        CadastrarClienteView cadCli = new CadastrarClienteView();
        cadCli.setVisible(true);
    }//GEN-LAST:event_cadastrar_clienteActionPerformed

    private void cadastrar_produçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_produçãoActionPerformed
        this.dispose();
        CadastrarProducao cadProd = new CadastrarProducao();
        cadProd.setVisible(true);
    }//GEN-LAST:event_cadastrar_produçãoActionPerformed

    private void editar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_clienteActionPerformed
        this.dispose();
        EditarClientesView editCli = new EditarClientesView();
        editCli.setVisible(true);
    }//GEN-LAST:event_editar_clienteActionPerformed

    private void editar_produçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_produçãoActionPerformed
        this.dispose();
        EditarProducaoView editProd = new EditarProducaoView();
        editProd.setVisible(true);
    }//GEN-LAST:event_editar_produçãoActionPerformed

    private void listar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listar_clienteActionPerformed
        this.dispose();
        ListarClientesView listCli = new ListarClientesView();
        listCli.setVisible(true);
    }//GEN-LAST:event_listar_clienteActionPerformed

    private void listar_produçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listar_produçãoActionPerformed
        this.dispose();
        ListarProducaoView listProd = new ListarProducaoView();
        listProd.setVisible(true);
    }//GEN-LAST:event_listar_produçãoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Sair;
    private javax.swing.JMenu cadastrar;
    private javax.swing.JMenuItem cadastrar_cliente;
    private javax.swing.JMenuItem cadastrar_produção;
    private javax.swing.JMenu editar;
    private javax.swing.JMenuItem editar_cliente;
    private javax.swing.JMenuItem editar_produção;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu listar;
    private javax.swing.JMenuItem listar_cliente;
    private javax.swing.JMenuItem listar_produção;
    // End of variables declaration//GEN-END:variables
}
